In [ ]:
# import the required lib
import numpy as np
import pandas as pd\

# read the data
df = pd.read_csv('/content/emp.csv')

# Visualize the dataset
df

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1.0,35.0,5.0,8.0,1.0,0.0,49.0,0.0
1,65141,Operations,region_22,Bachelor's,m,other,1.0,30.0,5.0,4.0,0.0,0.0,60.0,0.0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1.0,34.0,3.0,7.0,0.0,0.0,50.0,0.0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2.0,39.0,1.0,10.0,0.0,0.0,50.0,0.0
4,48945,Technology,region_26,Bachelor's,m,other,1.0,45.0,3.0,2.0,0.0,0.0,73.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30591,13894,Technology,region_2,Bachelor's,f,other,1.0,46.0,5.0,13.0,1.0,0.0,81.0,0.0
30592,31921,Operations,region_11,Master's & above,m,sourcing,1.0,45.0,2.0,18.0,1.0,0.0,57.0,0.0
30593,69703,Technology,region_27,Bachelor's,m,other,1.0,41.0,2.0,6.0,0.0,0.0,77.0,0.0
30594,39524,Sales & Marketing,region_22,Bachelor's,m,other,1.0,42.0,1.0,6.0,1.0,1.0,47.0,0.0
30595,70200,Sales & Marketing,region_23,Master's & above,m,sour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.head(n=12)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,region_7,Master's & above,f,sourcing,1.0,35.0,5.0,8.0,1.0,0.0,49.0,0.0
1,65141,Operations,region_22,Bachelor's,m,other,1.0,30.0,5.0,4.0,0.0,0.0,60.0,0.0
2,7513,Sales & Marketing,region_19,Bachelor's,m,sourcing,1.0,34.0,3.0,7.0,0.0,0.0,50.0,0.0
3,2542,Sales & Marketing,region_23,Bachelor's,m,other,2.0,39.0,1.0,10.0,0.0,0.0,50.0,0.0
4,48945,Technology,region_26,Bachelor's,m,other,1.0,45.0,3.0,2.0,0.0,0.0,73.0,0.0
5,58896,Analytics,region_2,Bachelor's,m,sourcing,2.0,31.0,3.0,7.0,0.0,0.0,85.0,0.0
6,20379,Operations,region_20,Bachelor's,f,other,1.0,31.0,3.0,5.0,0.0,0.0,59.0,0.0
7,16290,Operations,region_34,Master's & above,m,sourcing,1.0,33.0,3.0,6.0,0.0,0.0,63.0,0.0
8,73202,Analytics,region_20,Bachelor's,m,other,1.0,28.0,4.0,5.0,0.0,0.0,83.0,0.0
9,28911,Sales & Marketing,region_1,Master's & above,m,sourcing,1.0,32.0,5.0,5.0,1.0,0.0,54.0,0.0
10,29934,Technology,region_23,NaN,m,sourcing,1.0,30.0,NaN,1.0,0.0,0.0,77.0,0.0
11,49017,Sales & Marketing,region_7,Bachelor's,f,sourcing,1.0,35.0,5.0,3.0,1.0,0.0,50.0,1.0

In [ ]:
df.tail(n=12)

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
30584,25779,Procurement,region_2,Bachelor's,f,sourcing,1.0,56.0,3.0,2.0,0.0,0.0,67.0,0.0
30585,54115,Sales & Marketing,region_8,Master's & above,m,sourcing,1.0,32.0,1.0,6.0,0.0,0.0,47.0,0.0
30586,19709,Sales & Marketing,region_27,Master's & above,m,other,1.0,35.0,3.0,10.0,0.0,0.0,48.0,0.0
30587,3816,Legal,region_13,Bachelor's,m,sourcing,1.0,34.0,3.0,3.0,0.0,0.0,62.0,0.0
30588,13672,Sales & Marketing,region_2,Bachelor's,m,sourcing,2.0,30.0,1.0,5.0,0.0,0.0,44.0,0.0
30589,265,Procurement,region_2,Master's & above,f,other,1.0,58.0,4.0,26.0,0.0,0.0,71.0,0.0
30590,37983,Sales & Marketing,region_28,Bachelor's,f,other,2.0,33.0,3.0,6.0,0.0,0.0,48.0,0.0
30591,13894,Technology,region_2,Bachelor's,f,other,1.0,46.0,5.0,13.0,1.0,0.0,81.0,0.0
30592,31921,Operations,region_11,Master's & above,m,sourcing,1.0,45.0,2.0,18.0,1.0,0.0,57.0,0.0
30593,69703,Technology,region_27,Bachelor's,m,other,1.0,41.0,2.0,6.0,0.0,0.0,77.0,0.0
30594,39524,Sales & Marketing,region_22,Bachelor's,m,other,1.0,42.0,1.0,6.0,1.0,1.0,47.0,0.0
30595,70200,Sales & Marketing,region_23,Master's & above,m,sour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30596 entries, 0 to 30595
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           30596 non-null  int64
 1   department            30596 non-null  object
 2   region                30596 non-null  object
 3   education             29211 non-null  object
 4   gender                30596 non-null  object
 5   recruitment_channel   30596 non-null  object
 6   no_of_trainings       30595 non-null  float64
 7   age                   30595 non-null  float64
 8   previous_year_rating  28272 non-null  float64
 9   length_of_service     30595 non-null  float64
 10  KPIs_met >80%         30595 non-null  float64
 11  awards_won?           30595 non-null  float64
 12  avg_training_score    30595 non-null  float64
 13  is_promoted           30595 non-null  float64
dtypes: float64(8), int64(1), object(5)
memory usage: 3.3+ MB

In [ ]:
df.isnull()

,employee_id,department,region,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30591,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30592,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30593,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30594,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30595,False,False,False,False,False,False,True,True,True,True,True,True,True,True

df.isnull().sum()

In [ ]:
df.isnull().sum()

employee_id                0
department                 0
region                     0
education               1385
gender                     0
recruitment_channel        0
no_of_trainings            1
age                        1
previous_year_rating    2324
length_of_service          1
KPIs_met >80%              1
awards_won?                1
avg_training_score         1
is_promoted                1
dtype: int64

In [ ]:
df['age'].mean()

np.float64(34.792613172086945)

In [ ]:
df['age'].median()

33.0

In [ ]:
df['gender'].mode()

0    m
Name: gender, dtype: object

In [ ]:
df = df.drop('region',axis=1)
df.head()

,employee_id,department,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted
0,65438,Sales & Marketing,Master's & above,f,sourcing,1.0,35.0,5.0,8.0,1.0,0.0,49.0,0.0
1,65141,Operations,Bachelor's,m,other,1.0,30.0,5.0,4.0,0.0,0.0,60.0,0.0
2,7513,Sales & Marketing,Bachelor's,m,sourcing,1.0,34.0,3.0,7.0,0.0,0.0,50.0,0.0
3,2542,Sales & Marketing,Bachelor's,m,other,2.0,39.0,1.0,10.0,0.0,0.0,50.0,0.0
4,48945,Technology,Bachelor's,m,other,1.0,45.0,3.0,2.0,0.0,0.0,73.0,0.0

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
display(df.head())

,employee_id,department,education,gender,recruitment_channel,no_of_trainings,age,previous_year_rating,length_of_service,KPIs_met >80%,awards_won?,avg_training_score,is_promoted,gender_encoded
0,65438,Sales & Marketing,Master's & above,0,sourcing,1.0,35.0,5.0,8.0,1.0,0.0,49.0,0.0,0
1,65141,Operations,Bachelor's,1,other,1.0,30.0,5.0,4.0,0.0,0.0,60.0,0.0,1
2,7513,Sales & Marketing,Bachelor's,1,sourcing,1.0,34.0,3.0,7.0,0.0,0.0,50.0,0.0,1
3,2542,Sales & Marketing,Bachelor's,1,other,2.0,39.0,1.0,10.0,0.0,0.0,50.0,0.0,1
4,48945,Technology,Bachelor's,1,other,1.0,45.0,3.0,2.0,0.0,0.0,73.0,0.0,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30596 entries, 0 to 30595
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   employee_id           30596 non-null  int64
 1   department            30596 non-null  object
 2   education             29211 non-null  object
 3   gender                30596 non-null  int64
 4   recruitment_channel   30596 non-null  object
 5   no_of_trainings       30595 non-null  float64
 6   age                   30595 non-null  float64
 7   previous_year_rating  28272 non-null  float64
 8   length_of_service     30595 non-null  float64
 9   KPIs_met >80%         30595 non-null  float64
 10  awards_won?           30595 non-null  float64
 11  avg_training_score    30595 non-null  float64
 12  is_promoted           30595 non-null  float64
 13  gender_encoded        30596 non-null  int64
dtypes: float64(8), int64(3), object(3)
memory usage: 3.3+ MB